// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgYSip6VaQrKKCeu3NcuAerhJxID5rjIo',
    appId: '1:126172509323:web:1f785848a2dbf0c5fe108e',
    messagingSenderId: '126172509323',
    projectId: 'comic-book-store-d46da',
    authDomain: 'comic-book-store-d46da.firebaseapp.com',
    storageBucket: 'comic-book-store-d46da.firebasestorage.app',
    measurementId: 'G-H5KW4P94MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkNowEkorm53k46cW3wktjo5eFLtPxsqQ',
    appId: '1:126172509323:android:de42d16c66f01e75fe108e',
    messagingSenderId: '126172509323',
    projectId: 'comic-book-store-d46da',
    storageBucket: 'comic-book-store-d46da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3AjZdoenxPNaEbmy7Id8FC7xWq2OXkuM',
    appId: '1:126172509323:ios:66906326ec53e594fe108e',
    messagingSenderId: '126172509323',
    projectId: 'comic-book-store-d46da',
    storageBucket: 'comic-book-store-d46da.firebasestorage.app',
    iosBundleId: 'com.example.comicBookStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3AjZdoenxPNaEbmy7Id8FC7xWq2OXkuM',
    appId: '1:126172509323:ios:66906326ec53e594fe108e',
    messagingSenderId: '126172509323',
    projectId: 'comic-book-store-d46da',
    storageBucket: 'comic-book-store-d46da.firebasestorage.app',
    iosBundleId: 'com.example.comicBookStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgYSip6VaQrKKCeu3NcuAerhJxID5rjIo',
    appId: '1:126172509323:web:cc840c397c6c9652fe108e',
    messagingSenderId: '126172509323',
    projectId: 'comic-book-store-d46da',
    authDomain: 'comic-book-store-d46da.firebaseapp.com',
    storageBucket: 'comic-book-store-d46da.firebasestorage.app',
    measurementId: 'G-E4R4WG4HGN',
  );
}
